version: '3.8'
services:
#  postgres-auth:
#    image: postgres:14.2
#    environment:
#      - POSTGRES_DB=azor-shop-spring-rest-auth
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - '5433:5432'
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
#      interval: 5s
#      timeout: 1s
#      retries: 2

  postgres-core:
    image: postgres:14.2
    environment:
      - POSTGRES_DB=students
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 2

#  flyway:
#    image: boxfuse/flyway
#    command:
#      -url=jdbc:postgresql://postgres:5432/azor-shop-spring-rest-auth -schemas=public -user=postgres -password=postgres -connectRetries=30 migrate
#    volumes:
#      - ./flyway:/flyway/sql
#    depends_on:
#      - postgres

#  redis:
#    image: 'bitnami/redis:latest'
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    ports:
#      - "6379:6379"

